pool:
  vmImage: ubuntu-latest

steps:

#- task: Gradle@3
#  inputs:
#    gradleWrapperFile: 'gradlew'
#    tasks: 'build'
#    publishJUnitResults: true
#    testResultsFiles: '**/TEST-*.xml'
#    javaHomeOption: 'JDKVersion'
#    sonarQubeRunAnalysis: false
#    spotBugsAnalysis: false
#  displayName: 'Build Plugin'

#- script: |
#    chmod +x gradlew
#    ./gradlew clean build
#  displayName: 'Build'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonarcloud'
    organization: 'DevOps-Foundationv2'
    projectKey: 'DevOps-Foundation-v2_pet-clinic'
    projectName: 'pet-clinic'
  displayName: 'Preparing Sonarqube Environment'
    
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: "sonarqube"
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'
  displayName: 'Analyze current Branch'
    
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish Analysis Results'